### ISSUE TITLE
Minimal API

### ISSUE THREAD

**Issue by barodeur** [ashlynbaum/yogainthepark#2]
**Bootstrapping**
- [x] Define API endpoints for events by writing a documentation #6 
- [x] Implement the endpoints using the mocks #8 
- [ ] Remove the mocks and use MongoDB #9 
- [x] Deploy this first version of the API to heroku
- [ ] Update event content #10 
- [ ] User registration & authentication & Check user authorization for managing events #13 
- [ ] Picture upload for events
- [ ] User profile editing
- [ ] Facebook login

**Comment by barodeur** [comment]
@ashlynbaum I just updated the description of that Issue so it's reflecting the next assignment. Everything remains uncheck as the PR #6 is not merged yet.
